# Generated by Django 4.0.6 on 2022-07-25 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=30)),
                ('subheading', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
